### ISSUE TITLE
wrapper scan_ports exception behavior

### ISSUE THREAD

**Issue by ChrisChoke** [paulober/pyboard-serial-com#3]
Hey Paul,

as i tested my last commit i was wondering about a behavior.

if you use ```python3 wrapper.py --scan-ports``` i got something like ```/,d``` printed out. this is the case if you end up in the exception block of find_pico_ports() function.
if the function return normal we return a list with a tuple within, line 108:

https://github.com/paulober/pyboard-serial-com/blob/49cb1b1bf5cfc80c87cf10bed8a8316266ef45d8/scripts/wrapper.py#L108-L113

but in exception on line 112 we return a list with a string inside. i think we need something like

```python3
if isinstance(ports[0], tuple):
    print("\n".join(map(lambda x: str(f'{x[0]},{x[1]}'), ports))+"\n"+EOO, flush=True)
else:
    print("\n".join(map(lambda x: str(f'{x}'), ports))+"\n"+EOO, flush=True)
```
at

https://github.com/paulober/pyboard-serial-com/blob/49cb1b1bf5cfc80c87cf10bed8a8316266ef45d8/scripts/wrapper.py#L734

or return a tuple in the list with a defaulted hard coded baudrate or something.

and if the function return normal but i plugged in a unsupported device the function returned with an empty list, what i think thats okay. because else we maybe get the device returned from the exception block.

i hope you can understand what i mean :-)

i dont dare submit a suggestion in that case, because i am a hobby developer 😊

Chris

**Comment by paulober** [comment]
Thanks for reporting, i finally fixed it.
