### ISSUE TITLE
Request to add WaveShare device to the supported list

### ISSUE THREAD

**Issue by minkyn** [paulober/pyboard-serial-com#4]
WaveShare manufactured many boards based on RP2040, for example:
https://www.waveshare.com/wiki/RP2040-Plus

It shares the same VID (0x2E8A) as Pico, but has a different PID as 0x1020. It would be great if WaveShare's PID can be added to the supported list as well.

**Comment by paulober** [comment]
I added some:
```
0x1020,
    0x101F,
    0x1020,
    0x1021,
    0x1086,
```
Do you have some other to add?

**Comment by minkyn** [comment]
That looks terrific! (0x1020 got added twice though)
